geometries:
  - name: triangle
    file: triangle.obj
  - name: rectangle
    file: rectangle.obj
  - name: cube
    file: cube.obj
  - name: cylinder
    file: cylinder.obj
  - name: sphere
    file: sphere.obj
