materials:
  - name: basic
    file: basic.yaml
  - name: wireframe
    file: wireframe.yaml
  - name: texture
    file: texture.yaml
  - name: normalised
    file: normalised.yaml
  - name: ceed
    file: ceed.yaml
  - name: barycentric
    file: barycentric.yaml
  - name: wobbler
    file: wobbler.yaml
